server:
  port: 8087

spring:
  application:
    name: SpringCloudZull

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    users:
      path: /users/**
      serviceId: SpringCloudEurekaServerProducer

ribbon:
  eureka:
    enabled: false